import type { Metadata } from "next";
import { Geist, Geist_Mono ,Alexandria } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/page";
import Footer from "./footer/Footer";


const alexandria = Alexandria({
  variable: "--font-alexandria",
  subsets: ["arabic"],
});



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wekan",
  description: "Generated by create Wekan",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${alexandria.className} ${alexandria.className} h-full antialiased`}
    >

      <body className={`${alexandria.className} ${alexandria.className}min-h-full flex flex-col`}>
    <Navbar/>
{children}
    <Footer/>
      </body>
    </html>
  );
}
